#!/usr/bin/env bash

if
  [[ -s "/home/test/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/environment" ]]
then
  source "/home/test/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/environment"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/test/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/environment'" >&2
  exit 1
fi
