#!/usr/bin/env bash

if
  [[ -s "/home/test/.rvm/gems/ruby-2.3.3/environment" ]]
then
  source "/home/test/.rvm/gems/ruby-2.3.3/environment"
  exec racc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/test/.rvm/gems/ruby-2.3.3/environment'" >&2
  exit 1
fi
